Repository cityofaustin/atd-knack, pull requests merged in 2022-08, with the labels that each got.

#115 Added big button to GIS QA page
  code/signs-markings/signs-markings.js
Labels: JavaScript, Knack

#113 Disable TCP Application Breadcrumbs
  code/right-of-way/right-of-way.js
Labels: enhancement, JavaScript, Knack, new feature

#114 Remove Back Links for TCP Application
  code/right-of-way/right-of-way.css
Labels: enhancement, CSS, Knack, new feature

#116 Update Big Button code for ROW portal
  code/right-of-way/right-of-way.js
Labels: JavaScript, Knack

#117 Re-add Contractor Work Order Big button
  code/signs-markings/signs-markings.js
Labels: JavaScript, Knack
