Repository cityofaustin/atd-knack, pull requests merged in 2022-04, with the labels that each got.

#89 Update Customer Page Scenes for TIA Access Code Update
  code/transportation-development-services/tds.css
Labels: enhancement, CSS, Knack

#88 Removed/Updated Customer Pages for TIA Access Code Update
  code/transportation-development-services/tds.js
Labels: enhancement, JavaScript, Knack

#86 Updated Big Buttons for Portal page
  code/street-banner/street-banner.js
Labels: enhancement, JavaScript, Knack

#87 Update street-banner.js
  code/street-banner/street-banner.js
Labels: JavaScript, Knack

#90 Adding Big Buttons to Customer Portal page
  code/shared-mobility/shared-mobility-smrt.js
Labels: JavaScript, Knack

#91 URL banner changes to big button navigation
  code/street-banner/street-banner.js
Labels: JavaScript, Knack

#92 Big button URL change on Reservations page
  code/street-banner/street-banner.js
Labels: JavaScript, Knack

#93 updated Customer Action button size
  code/street-banner/street-banner.css
Labels: CSS, Knack

#94 Updated big button URLs for work orders
  code/street-banner/street-banner.js
Labels: JavaScript, Knack
