Repository cityofaustin/atd-knack, pull requests merged in 2023-01, with the labels that each got.

#128 First commit for ATD Forms CSS for Traffic Signal Design Manual Submissions
  code/atd-forms/atd-forms.css
Labels: CSS, Knack, new feature

#129 Disable Nav Links for New TCP Application JS
  code/right-of-way/right-of-way.js
Labels: enhancement, JavaScript, Knack

#130 Disable Back Links for New TCP Application CSS
  code/right-of-way/right-of-way.css
Labels: enhancement, CSS, Knack

#131 Mitigation Editor Update - Map iframe & Mitigation Table Summaries
  code/transportation-development-services/tds.js
Labels: JavaScript, new feature, cleanup

#132 Mitigation Editor Update for Back Links
  code/transportation-development-services/tds.css
Labels: enhancement, CSS, Knack

#133 Traffic Register Search Directory Update JS
  code/traffic-register/traffic-register.js
Labels: documentation, enhancement, JavaScript, Knack, cleanup

#134 Traffic Register Search Directory Update CSS
  code/traffic-register/traffic-register.css
Labels: enhancement, CSS, Knack, cleanup

#127 First commit for all ATD Forms JS for Traffic Signal Design Manual Submissions
  code/atd-forms/atd-forms.js
Labels: JavaScript, Knack, new feature

#138 Update street-banner.js
  code/street-banner/street-banner.js
Labels: JavaScript, Knack
